version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo building
      - sam build
      - sam package --s3-bucket hello-world-sam-bucket --output-template-file hello-world-template.yml
artifacts:
  type: zip
  files:
    - hello-world-template.yml