AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.8
    Timeout: 180
    Environment:
      Variables:
        DYNAMODB_TABLE: $Ref NotitiesTable

Resources:
  NotitiesApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: live
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: swagger.yaml

  NotitiesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: notities
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnit: 5
        WriteCapacityUnits: 5
      Tags:
        AppType: Serverless

  SelectOneFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: selectOne/
      Handler: lambda_function.lambda_handler
      Policies: AmazonDynamoDBFullAccess
      Events:
        Api:
          Type: Api
          Properties:
            Path: /notities/{notitieId}
            Method: get
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Canary10Percent5Minutes

  CreateOneFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: createOne/
      Handler: lambda_function.lambda_handler
      Policies: AmazonDynamoDBFullAccess
      Events:
        Api:
          Type: Api
          Properties:
            Path: /notities
            Method: post
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Canary10Percent5Minutes
Outputs:
  Endpoint:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Sub: https://${NotitiesApiGateway}.execute-api.${AWS::Region}.amazonaws.com/